version: '2.1'
executors:
  docker:
    docker:
      - image: docker:stable
jobs:
  lint-dockerfile:
    filters:
      branches:
        only:
          - karsajobs-ui
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Linting Dockerfiles with Hadolint
          command: |
            docker run --rm --interactive hadolint/hadolint < Dockerfile
  build-app-karsajobs-ui:
    filters:
      branches:
        only:
          - karsajobs-ui
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t karsajobs-ui:latest .
      - run:
          name: Push Docker image
          command: |
            docker tag karsajobs:latest ghcr.io/filahaa/karsajobs-ui:latest
            docker push ghcr.io/filahaa/karsajobs-ui:latest
workflows:
  lint-dockerfile:
    jobs:
      - lint-dockerfile
  build-app-karsajobs:
    jobs:
      - build-app-karsajobs-ui