version: '2.1'
executors:
  docker:
    docker:
      - image: docker:stable
jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Linting Dockerfiles with Hadolint
          command: |
            docker run --rm --interactive hadolint/hadolint < Dockerfile
  test-app:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t karsajobs:latest .
      - run:
          name: Push Docker image
          command: |
            docker tag karsajobs:latest ghcr.io/filahaa/karsajobs:latest
            docker push ghcr.io/filahaa/karsajobs:latest
workflows:
  lint-dockerfile:
    jobs:
      - lint-dockerfile
  test-app:
    jobs:
      - test-app
  build-app-karsajobs:
    jobs:
      - build-app-karsajobs