version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker run --rm --interactive hadolint/hadolint < Dockerfile
  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t karsajobs-ui:latest .
      - run:
          name: Push Docker image
          command: |
            echo $TOKEN_GITHUB_PACKAGES | docker login ghcr.io -u filahaa --password-stdin
            docker tag karsajobs:latest ghcr.io/filahaa/karsajobs-ui:latest
            docker push ghcr.io/filahaa/karsajobs-ui:latest

workflows:
    lint-dockerfile:
      jobs:
        - lint-dockerfile:
            filters:
              branches:
                only:
                  - karsajobs-ui
    build-app-karsajobs-ui:
      jobs:
        - build-app-karsajobs-ui:
            filters:
              branches:
                only:
                  - karsajobs-ui